services:
  backend:
    build:
      context: examples/todo-example
      dockerfile: Dockerfile
    container_name: automation-backend
    ports:
      - "8008:8085"

  frontend:
    build:
      context: ui
      dockerfile: Dockerfile
    container_name: automation-frontend
    ports:
      - "8009:3000"
    environment:
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    depends_on:
      - backend